REGEX_PIDS_PATTERN : str = r'<li data-node-id="(\d+)"\s+data-node-publishdate="(\d+)"\s+class="([^"]*)"\s+itemscope\s+itemtype="([^"]*)">(.*?)(?=\s*<\/div>\s*<\/div>\s*<\/li>)'
REGEX_INNER_CONTENT_CLASS: str = r'<div class="js-post__content-text restore h-wordwrap"\s+itemprop="text">(.*?) </div>'
REGEX_REMOVE_SPECIAL_CHARACTERS : str = r'[\r\n\t]'
REGEX_REPLACE_IMAGE_TITLE : str = r'<img src=".*?" border="0" alt="" title="(\w+)" smilieid="\d+" class="inlineimg" />'
REGEX_REPLACE_QUOT : str = r'&quot;www&quot;'
REGEX_REMOVE_ADDITIONAL_WHITESPACES_BETWEEN_DOT : str = r'\.( +)'
REGEX_REMOVE_POST_SIGNATURE_RESTORE : str = r'<div class="post-signature restore">(.*?)(?=\s*<\/div>\s*<\/div>)'
REGEX_BBCODE_POSTED_BY_CONTENT : str = r'<div class="bbcode_postedby">(.*?)</strong>'
REGEX_MESSAGE_CONTENT : str = r'<div class="message">(.*?)</div>'
REGEX_BBCODE_CONTAINER : str = r'<div class="bbcode_container">(.*?)(?=\s*<\/div>\s*<\/div>)'
REGEX_REMOVE_SPAN_CONTENT : str = r'<span style="color:silver">(.*?)</span>'
REGEX_REMOVE_CLOSING_DIVS : str = r'</div>'
REGEX_REMOVE_BRS : str = r'<br />'
REGEX_CODE : str = r'<pre class="bbcode_code" (style="[^"]+")>(.*?)<\/pre>'
REGEX_CODE_TRANSFORMER : str = r'(RewriteEngine On)(RewriteCond %{HTTP_HOST} [!^www\.\r\n]+)(RewriteRule .+? [R=301,L])'
REGEX_REMOVE_A_TAG : str = r'<a[^>]*>(.*?)</a>'
REGEX_LOWECASE_NEAR_TO_UPPERCASE : str = r'([a-z])([A-Z])'
REGEX_REMOVE_BBCODE : str = r'<div class="bbcode_container"><div class="bbcode_description">Code:'